### ISSUE TITLE
deployment module always tries to register Artemis JMS CF for reflection

### ISSUE THREAD

**Issue by gemmellr** [quarkiverse/quarkus-pooled-jms#107]
When trying to use quarkus-pooled-jms with a client other than the Artemis JMS client, a warning is emitted during native builds due to failure to register the ActiveMQConnectionFactory class for reflection:

```
Warning: Could not resolve org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory for reflection configuration. Reason: java.lang.ClassNotFoundException: org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.
```

Presumably this is because it always tries to register it, without checking to see if it is present:
https://github.com/quarkiverse/quarkus-pooled-jms/blob/b38940397fc9fe8567521bbdd8532fd62da47bf3/deployment/src/main/java/io/quarkiverse/messaginghub/pooled/jms/deployment/PooledJmsProcessor.java#L32-L34

It clearly shouldn't if it isn't present. It isnt clear to me that that it should be doing so even if it is present.

**Comment by zhfeng** [comment]
Yeah, it should be removed in `main` branch but it seems that this registration still be needed in `1.x`. I think there is something diffierent with `org.messaginghub:pooled-jms` between `3.1.0` and `2.0.5`

**Comment by gemmellr** [comment]
The only change I recall making between 2.x and 3.x is that there used to be some checks on whether a given javax.jms.ConnectionFactory actually implemented certain methods, allowing it to still work with JMS 1.1 impls that didnt implement bits newer than them.  Those were removed with the switch to jakarta.jms.ConnectionFactory since all jakarta impls have to be 3.x providers.

Still feels like quarkus-artemis should be the thing doing registrations in any case.
