### ISSUE TITLE
provide API to close pooled connections

### ISSUE THREAD

**Issue by sjhiggs** [quarkiverse/quarkus-pooled-jms#248]
In some cases, it is desirable to force all the connections in the pool to close/re-open, e.g. when restarting  a Camel route.  This allows clients to re-balance when connecting to brokers in a cluster.

For example, in a clustered broker environment, sometimes broker restarts can cause clients to migrate to a small subset of the available brokers.  A method to close the connections in the pool would allow the client to load balance across the full set of available brokers.

**Comment by zhfeng** [comment]
Hi @sjhiggs can you check with the PR
- https://github.com/quarkiverse/quarkus-pooled-jms/pull/249

You can use the following codes in your application to clear all the connections. The new connection will be created in the next call to the connection pool.

```java
@Inject
PooledJmsWrapper wrapper;

void clear() {
    wrapper.clearAll();
}
```
And make sure no connection has been used before call `clear()` method. All of the connections will be closed and removed from pool.

**Comment by sjhiggs** [comment]
This works, thanks!

**Comment by zhfeng** [comment]
@sjhiggs I make there releases to add this feature.

- `2.4.0` with the lastest Quarkus
- `2.3.2` with the Quarkus 3.8
- `2.1.2` with the Quarkus 3.2
