### ISSUE TITLE
XA Support Documentation Clarification

### ISSUE THREAD

**Issue by mkomadel** [quarkiverse/quarkus-pooled-jms#305]
Hi, according to the [documentation](https://docs.quarkiverse.io/quarkus-pooled-jms/2.3.x/index.html) in the "[XA transaction support](https://docs.quarkiverse.io/quarkus-pooled-jms/2.3.x/index.html#_xa_transaction_support)" part, XA support is only available with quarkus-artemis-jms. But a few lines downwards, in "[Custom ConnectionFactory](https://docs.quarkiverse.io/quarkus-pooled-jms/2.3.x/index.html#_xa_transaction_support)" XA transactions are mentioned with regard to MQ connection factory (and the code example utilizes `MQXAConnectionFactory`). 
The question now is, are the XA trasactions supported also for MQ broker (or any other broker at that) or only for artemis broker? Thanks

**Comment by zhfeng** [comment]
Thanks @mkomadel - Yeah,  I think the XA is supported for IBM MQ as well but there is no such a relevant quarkiverse extension. So that's the reason you have to do a Custom ConnectionFactory.

**Comment by mkomadel** [comment]
@zhfeng  Thanks

**Comment by mkomadel** [comment]
@zhfeng Thanks

**Comment by mkomadel** [comment]
Thanks
