### ISSUE TITLE
Prepare for Quarkus 3.0.0

### ISSUE THREAD

**Issue by turing85** [quarkiverse/quarkus-pooled-jms#39]
In the advent of the Quarkus 3.0.0 release, we should prepare this extension.

We depend on [`quarkus-artemis-jms`](https://github.com/quarkiverse/quarkus-artemis), therefore we need builds of this extension in order to test compatibility.

Current release of `quarkus-artemis-jms`:[![Version](https://img.shields.io/maven-central/v/io.quarkiverse.artemis/quarkus-artemis-jms)](https://search.maven.org/artifact/io.quarkiverse.artemis/quarkus-artemis-jms)

**Comment by turing85** [comment]
Necessary import changes:
- `javax.enterprise` -> `jakarta.enterprise`
- `javax.inject` -> `jakarta.inject`
- `javax.transaction.TransactionManager` -> `jakarta.transaction.TransactionManager`
  - curiously enough, `javax.transaction.xa.XAResource` was not moved to `jakarta`

**Comment by turing85** [comment]
It seems that narayana has not yet been migrated to jakartaEE:

```
[ERROR] /eXchange/git/quarkiverse/quarkus-pooled-jms/runtime/src/main/java/io/quarkiverse/messaginghub/pooled/jms/PooledJmsWrapper.java:[48,28] cannot access javax.transaction.TransactionManager
  class file for javax.transaction.TransactionManager not found
[ERROR] /eXchange/git/quarkiverse/quarkus-pooled-jms/runtime/src/main/java/io/quarkiverse/messaginghub/pooled/jms/PooledJmsWrapper.java:[54,58] cannot access jakarta.jms.XAConnectionFactory
  class file for jakarta.jms.XAConnectionFactory not found
```

**Comment by turing85** [comment]
So this is a curious one. If we use `pooled-jms` version 2.0.5, we get the above error. If we use `pooled-jms` version 3.0.0, we have a version incompatibility in `jarkarta.jms-api`, since quarkus (and `quarkus-artemis-jms`) uses version `2.0.3`, while `org.messaginghub:pooled-jms` uses version `3.0.0`.

**Comment by turing85** [comment]
The version incompatibility is coming from `quarkus-artemis-jms`. The artemis jms client used pulls in `jarkarta.jms-api` in version `2.0.3`.

**Comment by zhfeng** [comment]
> `javax.transaction.TransactionManager` -> `jakarta.transaction.TransactionManager`
> * curiously enough, `javax.transaction.xa.XAResource` was not moved to `jakarta`

I think it is because this package is provided by Java SE. see [Jakarta Transaction spec](https://jakarta.ee/specifications/transactions/2.0/jakarta-transactions-spec-2.0.html#java-se)

**Comment by zhfeng** [comment]
https://jakarta.ee/specifications/messaging/

- Messaging 2.0 for Jakarta EE 8
- Messaging 3.0 for Jakarta EE 9
- Messaging 3.1 for Jakarta EE 10

And from quarkus-dev [Road to Quakrus 3](https://groups.google.com/g/quarkus-dev/c/xjHIBk6Mx7k), it will move to Jakarka EE 10. @maxandersen is it right?

**Comment by turing85** [comment]
With release `3.0.0.Alpha3` of `io.quarkiverse.artemis:quarkus-artemis-jms` and version `3.0.0` of `org.messaginghub:pooled-jms`, everything seems to work fine. We have to modify the configuration of the integration tests to enable the default configuration (adding `quarkus.artemis.enabled=true` to `application.properties`).

**Comment by turing85** [comment]
@zhfeng do you want to provide a branch for the migration? Or should I create a branch in my fork, and we transfer it later?

**Comment by zhfeng** [comment]
Thanks a lot @turing85 ! Please hold a branch in your fork. I willl creat a branch fro migration later. I still have some works on wrapping ConnectionFactory more generically and it might get rid of dependency on quarkus-artemis-jms.

**Comment by turing85** [comment]
[fork branch](https://github.com/turing85/quarkus-pooled-jms/tree/feature/39-prepare-for-quarkus-3)

**Comment by ppalaga** [comment]
What is the status of the migration? Is there any estimate when we could expect a release compatible with Quarkus 3?
